# Generated by Packer for ${vm_name}.

text
eula --agreed
firstboot --disable
skipx

lang ${locale}
keyboard --xlayouts='${keyboard_layout}'
timezone ${timezone} --utc

network --bootproto=dhcp --device=link --activate --onboot=yes --hostname=${host_name}.${hostname_domain}

rootpw --lock
user --name=${installer_username} --groups=wheel --plaintext --password=${installer_password}
authselect --useshadow --passalgo=sha512

selinux --enforcing
firewall --enabled --service=ssh
services --enabled=sshd,vmtoolsd,chronyd

bootloader --location=mbr --append="crashkernel=auto"
zerombr
clearpart --all --initlabel
autopart --type=lvm --fstype=xfs

reboot --eject

%packages --ignoremissing
@^minimal-environment
chrony
cloud-init
open-vm-tools
openssh-server
perl
python3
sudo
tar
vim-minimal
%end

%addon com_redhat_kdump --disable
%end

%post --log=/root/ks-post.log
set -euxo pipefail

cat >/etc/sudoers.d/90-${installer_username} <<'EOF'
${installer_username} ALL=(ALL) NOPASSWD: ALL
EOF
chmod 0440 /etc/sudoers.d/90-${installer_username}

systemctl enable sshd
systemctl enable vmtoolsd
systemctl enable chronyd

dnf -y clean all || true
rm -rf /tmp/* /var/tmp/*
%end
